parse_args:
parse_result: 
  - min: 1
    max: 3 
    char: a
    password: abcde
  - min: 1
    max: 3
    char: b
    password: cdefg
  - min: 2
    max: 9
    char: c
    password: ccccccccc
part1_args:
part1_result: 2
part2_args:
part2_result: 1
