parse_args:
parse_result: 
  - ['.', '.', '#', '#', '.', '.', '.', '.', '.', '.', '.']
  - ['#', '.', '.', '.', '#', '.', '.', '.', '#', '.', '.']
  - ['.', '#', '.', '.', '.', '.', '#', '.', '.', '#', '.']
  - ['.', '.', '#', '.', '#', '.', '.', '.', '#', '.', '#']
  - ['.', '#', '.', '.', '.', '#', '#', '.', '.', '#', '.']
  - ['.', '.', '#', '.', '#', '#', '.', '.', '.', '.', '.']
  - ['.', '#', '.', '#', '.', '#', '.', '.', '.', '.', '#']
  - ['.', '#', '.', '.', '.', '.', '.', '.', '.', '.', '#']
  - ['#', '.', '#', '#', '.', '.', '.', '#', '.', '.', '.']
  - ['#', '.', '.', '.', '#', '#', '.', '.', '.', '.', '#']
  - ['.', '#', '.', '.', '#', '.', '.', '.', '#', '.', '#']

part1_args:
  slope:
    - right: 3
      down: 1
part1_result: 7
part2_args:
  slope:
    - right: 1
      down: 1
    - right: 3
      down: 1
    - right: 5
      down: 1
    - right: 7
      down: 1
    - right: 1
      down: 2
part2_result: 336
